version: '3.8'

services:
  fcgi-server:
    build: .
    container_name: fcgi-server
    expose:
      - "81"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:8080"  # localhost:80 -> nginx:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
    depends_on:
      - fcgi-server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

